name: Deploy to Firebase Functions

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Selecciona el proyecto/entorno a desplegar'
        required: true
        default: 'production-tss'
        type: choice
        options:
          - production-tss
          - production-alm181

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-env.yml
    with:
      environment: ${{ github.event.inputs.environment || 'production-tss' }}
    secrets:
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      APP_SECRET: ${{ secrets.APP_SECRET }}

  tag:
    needs: deploy
    uses: ./.github/workflows/tag.yml
    permissions:
     contents: write
    with:
      environment: ${{ github.event.inputs.environment || 'prod' }}
